version: '3'
services:
  mysql:
    container_name: mysql
    build: ./
    restart: always
    ports:
      - 3306:3306
    expose:
      - '3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: password